language: elixir
before_install:
  - wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
  - sudo dpkg -i erlang-solutions_1.0_all.deb
  - sudo apt-get update
  - sudo apt-get install erlang
  - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.4/Precompiled.zip
  - unzip -d elixir Precompiled.zip
addons:
  postgresql: '9.4'
notifications:
  email:
    recipients:
      - adam@apathydrive.com
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.rebar
  - mix local.hex --force
  - cp config/config.exs.example config/config.exs
  - cp config/test.exs.example config/test.exs
  - MIX_ENV=test mix do deps.get, compile
  - psql -c 'create database travis_ci_test;' -U postgres
  - mix ecto.migrate
  - pg_restore --dbname=travis_ci_test test/data/skills.dump
script:
  - mix test
env:
  - MIX_ENV=test
